dist: trusty
sudo: false

os:
  - linux
  - osx

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

install:
  - type -p cargo-install-update || travis_wait cargo install cargo-update
  - travis_wait cargo install-update -i cargo-update
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then
      travis_wait cargo install-update -i rustfmt-nightly
      cargo clippy -V;
      if [ $? == 0 ]; then
        travis_wait cargo install-update -i clippy;
      else
        travis_wait cargo install-update -i -f clippy;
      fi
    fi

script:
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo fmt -- --write-mode=diff
    fi
  - if [ $TRAVIS_RUST_VERSION == nightly ]; then
      cargo clippy -- -D warnings;
    fi
  - cargo build
  - cargo test
