language: rust

rust:
   - stable
   - beta
   - nightly

os:
   - linux
   - osx

install:
   - cargo install rustfmt
   - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo install clippy; fi

script:
   - cargo fmt -- --write-mode=diff
   - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo clippy; fi
