language: rust

rust:
   - stable
   - beta
   - nightly

cache: cargo

os:
   - linux
   - osx

install:
   - travis_wait cargo install rustfmt || true
   - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then travis_wait cargo install clippy || true; fi

script:
   - cargo fmt -- --write-mode=diff
   - if [[ $TRAVIS_RUST_VERSION == "nightly" ]]; then cargo clippy; fi
   - cargo build --verbose
   - cargo test --verbose
