[package]
name = "variant"
version = "0.1.0"
authors = ["Polydraw Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/polydraw/variant"
homepage = "https://github.com/polydraw/variant"
description = "Dynamic variant type"
